language: ruby
rvm:
  - 2.0.0
before_script:
  - cp config/database.heroku.yml config/database.yml
  - psql -c 'create database danielkeeton_test;' -U postgres
  - bundle exec rake db:migrate
  - export RUBY_GC_MALLOC_LIMIT=50000000
env:
  - SECRET_KEY=akasjbdflkajb3lkjablk3hjalkjshdflkja3lkah3lkjhaslkdjhal
